### ISSUE TITLE
Dojo de git

### ISSUE THREAD

**Issue by DafneM** [fga-eps-mds/2023-1-Alectrion-DOC#1]
O objetivo dessa issue é elaborar e guiar o dojo de git com os membros.

**Comment by mibasFerraz** [comment]
Iniciamos o dojo e já estamos quase terminando, também gravamos tudo para os que não puderam comparecer

**Comment by mibasFerraz** [comment]
O dojo foi finalizado e uma parte dos estudantes foram até a reunião e tiraram bom proveito do ensino realizado, uma outra parte assistiu posteriormente e também conseguiu realizar a atividade desenvolvida.
