### ISSUE TITLE
Dojo de docker 

### ISSUE THREAD

**Issue by DafneM** [fga-eps-mds/2023-1-Alectrion-DOC#2]
O objetivo dessa issue é elaborar e guiar o dojo de docker.

**Comment by AlineLermen** [comment]
Foram apresentados os conceitos básicos e utilidade do docker e docker compose.
Depois foi uma parte prática: quem ainda não tinha a ferramenta instalada, fez a instalação pra depois tentar subir um projeto de exemplo usando o docker compose. Quem já possuía docker instalado, já subiu direto o projeto de exemplo

A reunião foi gravada no teams.
