### ISSUE TITLE
US 01: Cadastrar equipamento

### ISSUE THREAD

**Issue by JoaoVitorFarias** [fga-eps-mds/2023-1-Alectrion-DOC#31]
# US 01: Cadastrar equipamento

**Descrição**
Eu como **funcionário do DSTI** gostaria de **cadastrar um equipamento** para **manter o registro dele.**

**Tarefas**

- [ ] #47
- [x] #46
- [x] #78
- [x] #41
- [x] #44 

**Critérios de Aceitação**

- [ ] Apenas usuário com perfil de ADMINISTRADOR poderá cadastrar equipamento;
- [ ] O usuário poderá cadastrar um equipamento:
1. **Tipo de Equipamento**; 
2. **Nº Tombamento**;
3. **Marca**;
4. **Modelo**:
5. **Nº Série**;
6. **Tipo de Aquisição**; (Juntamente com esse campo "6", deverá ter uma opção para marcar se o equipamento é **NOVO** ou **USADO**, sendo nesta última, para alguns casos de doação. Lembrando que doação pode ser NOVO também).
7. **Ano do Equipamento**;
8. **Data de Aquisição**
9. **Nº da Nota Fiscal**
10. **Descrição** (Campo para mencionar informações complementares ou pertinentes.
- [ ] Quando **Tipo de Equipamento** = **CPU**:
11. **Qtd. Memória RAM** (unidade em GB)
12. **Qtd. Armazenamento** (unidade em GB)
13. **Tipo de Armazenamento** (escolher **HD** ou **SSD**)
14. **Processador** (Modelos de Processadores)
- [ ] Quando **Tipo de Equipamento** = **MONITOR**:
11. **Tipo de Monitor** (escolher LCD ou LED)
12. **Tamanho do Monitor** (unidade em Polegadas)
- [ ] Quando **Tipo de Equipamento** = **ESTABILIZADOR** ou **NOBREAK**:
11. **Potência** (unidade em volt-ampère - VA)
- [ ] Tipos de equipamentos
ítem | Tipo de   Equipamentos
-- | --
1 | CPU
2 | MONITOR
3 | ESTABILIZADOR
4 | NOBREAK
5 | HUB
6 | SWITCH
7 | NOTEBOOK
8 | DATASHOW
9 | SCANNER
10 | IMPRESSORA
11 | ROTEADOR
12 | TABLET
13 | TV
14 | FAX
15 | TELEFONE
16 | SMARTPHONE
17 | PROJETOR
18 | TELA   DE PROJEÇÃO
19 | CÂMERA
20 | WEBCAM
21 | CAIXA   DE SOM
22 | IMPRESSORA   TÉRMICA
23 | LEITOR   DE CÓDIGO DE BARRAS / CCD
24 | MESA   DIGITALIZADORA
25 | LEITOR   BIOMÉTRICO
26 | RECEPTOR
27 | EXTRATOR   DE DADOS
28 | TRANSFORMADOR
29 | COLETOR   DE ASSINATURA
30 | KIT   CENÁRIO
31 | DISPOSITIVO   DE BIOMETRIA FACIAL
32 | SERVIDOR   DE REDE
33 | HD   EXTERNO
34 | PROTETOR   ELETRÔNICO

- [ ] Tipo de aquisição tem que ser um campo aberto para escrita 
- [ ] Todos os campos sao obrigatorios menos o "detalhes"

**Prótotipo**

 https://www.figma.com/file/AhRaOWwMEHpVvgCRN54j7S/ALECTRION?node-id=162-10

**Comment by AlineLermen** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2023-1-Alectrion-642e344a93873e001a61de85/issues/fga-eps-mds/2023-1-Alectrion-DOC/31?planning-poker) with Zenhub @DafneM @linktocaio @esteerlino @JPedroCh @luanatorress @lucasgbezerra @mibasFerraz @suzaneduarte

**Comment by guilhermepupak** [comment]
Critérios de Aceitação:

* Apenas usuário com perfil de ADMINISTRADOR poderá cadastrar equipamento, e editar;
* Após o cadastro de um equipamento, o usuário terá o tempo de até 5 minutos para exclui-lo, caso contrario a funcionalidade será desabilitada;
* Após movimentação não pode ser excluído o equipamento;

* Segue o campos GERAIS para cadastrar equipamentos (com exceção de CPU, MONITOR, ESTABILIZAR e NOBREAK):
1. **Tipo de Equipamento**; 
2. **Nº Tombamento**;
3. **Marca**;
4. **Modelo**:
5. **Nº Série**;
6. **Tipo de Aquisição**; (Juntamente com esse campo "6", deverá ter uma opção para marcar se o equipamento é **NOVO** ou **USADO**, sendo nesta última, para alguns casos de doação. Lembrando que doação pode ser NOVO também).
7. **Ano do Equipamento**;
8. **Data de Aquisição**
9. **Nº da Nota Fiscal**
10. **Descrição** (Campo para mencionar informações complementares ou pertinentes.

* Quando **Tipo de Equipamento** = **CPU**:
11. **Qtd. Memória RAM** (unidade em GB)
12. **Qtd. Armazenamento** (unidade em GB)
13. **Tipo de Armazenamento** (escolher **HD** ou **SSD**)
14. **Processador** (Modelos de Processadores)

* Quando **Tipo de Equipamento** = **MONITOR**:
11. **Tipo de Monitor** (escolher LCD ou LED)
12. **Tamanho do Monitor** (unidade em Polegadas)

* Quando **Tipo de Equipamento** = **ESTABILIZADOR** ou **NOBREAK**:
11. **Potência** (unidade em volt-ampère - VA)




Segue abaixo a tabela de **Tipo de Equipamentos**, para fazer o depara:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link id=Main-File rel=Main-File
href="file:///C:\Users\GUILHE~1\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\GUILHE~1\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>



ítem | Tipo de   Equipamentos
-- | --
1 | CPU
2 | MONITOR
3 | ESTABILIZADOR
4 | NOBREAK
5 | HUB
6 | SWITCH
7 | NOTEBOOK
8 | DATASHOW
9 | SCANNER
10 | IMPRESSORA
11 | ROTEADOR
12 | TABLET
13 | TV
14 | FAX
15 | TELEFONE
16 | SMARTPHONE
17 | PROJETOR
18 | TELA   DE PROJEÇÃO
19 | CÂMERA
20 | WEBCAM
21 | CAIXA   DE SOM
22 | IMPRESSORA   TÉRMICA
23 | LEITOR   DE CÓDIGO DE BARRAS / CCD
24 | MESA   DIGITALIZADORA
25 | LEITOR   BIOMÉTRICO
26 | RECEPTOR
27 | EXTRATOR   DE DADOS
28 | TRANSFORMADOR
29 | COLETOR   DE ASSINATURA
30 | KIT   CENÁRIO
31 | DISPOSITIVO   DE BIOMETRIA FACIAL
32 | SERVIDOR   DE REDE
33 | HD   EXTERNO
34 | PROTETOR   ELETRÔNICO



</body>

</html>
