### ISSUE TITLE
US 02: Editar equipamento

### ISSUE THREAD

**Issue by JoaoVitorFarias** [fga-eps-mds/2023-1-Alectrion-DOC#36]
# US 02: Editar equipamento

**Descrição**
Eu como **funcionário do DSTI** gostaria de **editar um equipamento** para **manter o registro atualizado**.

** Critérios de aceitação **

**Critérios de Aceitação**

- [ ] Apenas usuário com perfil de ADMINISTRADOR poderá editar equipamento;
- [ ] O usuário poderá atualizar os dados de um equipamento já cadastrado.
- [] Para equipamentos com campos especificos (monitor, CPU, estabilizador e nobreak) O tipo do equipamento não deve ser alterado após feito o cadastro do mesmo.
- [] Todos os campos gerais devem poder ser alterados

**Prótotipo**

 https://www.figma.com/file/AhRaOWwMEHpVvgCRN54j7S/ALECTRION?node-id=162-10

**Comment by guilhermepupak** [comment]
Critérios de Aceitação

[ok] Apenas usuário com perfil de ADMINISTRADOR poderá editar equipamento;

[ok] O usuário poderá atualizar os dados de um equipamento já cadastrado.

**Comment by guilhermepupak** [comment]
Critérios de Aceitação

- Apenas usuário com perfil de ADMINISTRADOR poderá editar equipamento;
- O usuário poderá atualizar os dados de um equipamento já cadastrado;
- Para equipamentos com campos específicos (Monitor, CPU, Estabilizador e Nobreak), o tipo do equipamento não deve ser alterado após feito o cadastro do mesmo;
- Todos os campos gerais podem poder ser alterados.
