### ISSUE TITLE
US 03: Excluir equipamento

### ISSUE THREAD

**Issue by JoaoVitorFarias** [fga-eps-mds/2023-1-Alectrion-DOC#37]
# US 03: Excluir equipamento

**Descrição**
Eu como **funcionário do DSTI** gostaria de **excluir um equipamento** para **remover o registro dele**.

**Critérios de Aceitação**

- [ ] Após o cadastro de um equipamento, o usuário terá o tempo de até **10 minutos** para exclui-lo, caso contrario a funcionalidade será desabilitada 
- [ ] Após movimentação não pode ser excluído o equipamento
- [ ] Apenas usuário com perfil de ADMINISTRADOR poderá excluir equipamento;

**Prótotipo**

 https://www.figma.com/file/AhRaOWwMEHpVvgCRN54j7S/ALECTRION?node-id=162-10

**Comment by guilhermepupak** [comment]
Critérios de Aceitação

Após o cadastro de um equipamento, o usuário terá o tempo de até **10 (DEZ) minutos** para exclui-lo, caso contrario a funcionalidade será desabilitada
Após movimentação não pode ser excluído o equipamento;
Apenas usuário com perfil de ADMINISTRADOR poderá excluir equipamento;

**Comment by guilhermepupak** [comment]
Critérios de Aceitação

- Após o cadastro de um equipamento, o usuário terá o tempo de até 10 minutos para exclui-lo, caso contrario a funcionalidade será desabilitada
- Após movimentação não pode ser excluído o equipamento;
- Apenas usuário com perfil de ADMINISTRADOR poderá excluir equipamento.
