### ISSUE TITLE
US 05: Registrar movimentação

### ISSUE THREAD

**Issue by AlineLermen** [fga-eps-mds/2023-1-Alectrion-DOC#50]
# US 05: Registrar movimentação

**Descrição**
Eu como funcionário do DSTI gostaria de registrar uma movimentação a fim de gerenciar a situação do(s) equipamento(s)

**Tarefas**

- [x] #80
- [x] #81
- [x] #79
- [x] #94
- [x] [BACK]  Avaliar criação de movimentação; 

**Critérios de Aceitação**

- [ ] A movimentação tem que armazenar os dados principais do equipamento;
- [ ] Tem que ser possível armazenar hora e data da movimentação;
- [ ] Deve ser possível representar o que essa movimentação vai gerar posteriormente (termo);
- [ ] Deve ser possível especificar de qual equipamento é a movimentação ;
- [ ] Necessário guardar quem é o responsável pela movimentação;

**Protótipo**

Link: https://www.figma.com/file/AhRaOWwMEHpVvgCRN54j7S/ALECTRION?type=design&node-id=410%3A126&t=bDiodLDQVMkPacMy-1

**Comment by guilhermepupak** [comment]
Critérios de Aceitação

A movimentação tem que armazenar os dados principais do equipamento;
Tem que ser possível armazenar hora e data da movimentação;
Deve ser possível representar o que essa movimentação vai gerar posteriormente;
Deve ser possível especificar de qual equipamento é a movimentação ;
Necessário guardar quem é o responsável pela movimentação;

além dos critérios acima, acrescentar o seguinte:
[ ] A movimentação tem que armazenar quais foram os locais por onde o equipamento transitou;
