### ISSUE TITLE
US 06: Visualizar histórico de movimentação

### ISSUE THREAD

**Issue by AlineLermen** [fga-eps-mds/2023-1-Alectrion-DOC#51]
# US 06: Visualizar histórico de movimentação

**Descrição**
Eu como funcionário do DSTI gostaria de conseguir visualizar o histórico de movimentações de determinado equipamento a fim de acompanhar o equipamento.

**Tarefas**

- [ ] Tarefa 1;
- [ ] Tarefa 2;

**Critérios de Aceitação**

- [ ] Critério 1;

**Comment by guilhermepupak** [comment]
Critérios de Aceitação:
- Qualquer usuário poderá consultar o histórico de movimentação dos equipamentos.
