### ISSUE TITLE
US 10: Gerar termo de baixa

### ISSUE THREAD

**Issue by AlineLermen** [fga-eps-mds/2023-1-Alectrion-DOC#56]
# US 10: Gerar termo de baixa

**Descrição**
Eu como funcionário do DSTI gostaria de gerar um termo de Baixa para quando o equipamento se torna sucata. 

**Tarefas**

- [ ] Criar modal para gerar pdf assim que a movimentação é cadastrada
- [ ] Gerar o PDF ao clicar em uma movimentação específica 
- [ ] Estilizar PDF conforme modelo 

**Critérios de Aceitação**

- [ ] Qualquer usuário poderá Gerar os Termos, com exceção do usuário com perfil de consulta.
- [ ] Quando o equipamento se torna SUCATA (TERMO DE BAIXA), ele saí da unidade de lotação atual, direto para sucata. Ou seja, não é necessário movimentar este equipamento para a INFORMATICA e depois baixá-lo.

**Comment by guilhermepupak** [comment]
Critérios de Aceitação

- Qualquer usuário poderá Gerar os Termos, com exceção do usuário com perfil de consulta.
- São 03 (três) os tipos de termos gerados: 
1º) TERMO DE RESPONSABILIDADE - quando o equipamento é lotado definitivamente em uma unidade;
2º) TERMO DE EMPRÉSTIMO - quando o equipamento é lotado temporariamente em uma unidade;
3º) TERMO DE BAIXA - quando o equipamento se torna sucata.
- Quando o equipamento se torna SUCATA (TERMO DE BAIXA), ele saí da unidade de lotação atual, direto para sucata. Ou seja, não é necessário movimentar este equipamento para a INFORMATICA e depois baixá-lo. 
- Além dos termos, a aplicação deverá ser gerar RELATÓRIOS por PERÍODO, dos termos gerados.
