### ISSUE TITLE
US 04: Listar equipamentos

### ISSUE THREAD

**Issue by AlineLermen** [fga-eps-mds/2023-1-Alectrion-DOC#64]
# US 04: Listar equipamentos

**Descrição**
Eu como funcionário do DSTI gostaria de listar os equipamentos já cadastrados para realizar o controle de estoque.

**Critérios de Aceitação**

- [ ] Ver ao mesmo tempo 10 equipamentos por página;
- [ ] Ver número de série de cada equipamento;
- [ ] Ver número de tombamento de cada equipamento;
- [ ] Conseguir filtrar equipamentos pela barra de pesquisa por tipo, número de série e número de tombamento de cada equipamento;
- [ ] Filtrar por tipo, marca, modelo, data de última movimentação, local e status.

**Protótipo**

Link: https://www.figma.com/file/AhRaOWwMEHpVvgCRN54j7S/ALECTRION?type=design&node-id=410%3A126&t=bDiodLDQVMkPacMy-1

**Comment by guilhermepupak** [comment]
Critérios de Aceitação

Ver ao mesmo tempo 10 equipamentos por página;
Ver número de série de cada equipamento;
Ver número de tombamento de cada equipamento;
Conseguir filtrar equipamentos pela barra de pesquisa por tipo, número de série e número de tombamento de cada equipamento;
Filtrar por tipo, marca, modelo, data de última movimentação, local e status.

Além dos critérios de listagem acima, solicito também:
[ ] Ver LOCAL de cada equipamento.
