### ISSUE TITLE
Roteiro para testes do usuário

### ISSUE THREAD

**Issue by mibasFerraz** [fga-eps-mds/2023-1-Alectrion-DOC#90]
**Descrição**
Esse roteiro vai mostrar o passo a passo para que o Pupak e o Dirlei consigam testar as funcionalidades desenvolvidas até o momento.

**Tarefas :** 
- [ ] Todos os passos executados e aprovados.

**Comment by linktocaio** [comment]
# Roteiro para testes do usuário

História(s) a ser(em) testada(s): **US 01** (#31 ), **US 2**(#36 ), **US 3**(#37 ), **US 4**(#64 )

Testadores: Guilherme e Dirlei

### Passos para os testes

Para cada passo executado abaixo, **marque a caixa de seleção** correspondente para indicar a correta execução do que foi pedido.

**Obs.:** Caso seja necessário indicar mudanças ou não conformidade aos critérios de aceitação da(s) respectiva(s) história(s), responda ao presente roteiro com um comentário, marcando o "@" dos _assignees_ (MDS) e pelo menos um "@" dos EPS.

1. Acesse a aplicação em: https://alectrion-2023.herokuapp.com
- [ ] ok

2. Navegue para o controle de equipamentos na barra de navegação lateral.
- [ ] ok

3. Na tela de contorle, clique no botão "Cadastrar Equipemento"
- [ ] ok

4. Ao cadastrar o equipamento, verifique que, para os equipamentos como "CPU; MONITOR; ESTABILIZADOR e NOBREAK", as seguintes informações adicionais aparecem (cada qual pertinente ao equipamento em questão):
- [ ] Memória RAM (referente a CPU)
- [ ] Armazenamento (referente a CPU)
- [ ] Tipo de armazenamento (referente a CPU)
- [ ] Processador (referente a CPU)
- [ ] Tipo do monitor (referente a monitor)
- [ ] Tamanho do monitor (referente a monitor)
- [ ] Potência (referente a NoBreak)

5. Verifique se apos o correto preenchimento dos campos, ao clicar no botão de "confirmar":
- [ ] Um pop-up aparece confirmando o sucesso.

6. Verifique se apos o preenchimento errado dos campos, ao clicar no botão de "confirmar":
- [ ] Um pop-up aparece relatando erro.

7. Verifique se apos o sucesso de um cadastro de equipamentos o mesmo aparece na listagem na pagina de controle de equipamentos.
- [ ] ok

8. Verifique se ao clicar no equipamento cadastrado na listagem o mesmo:
- [ ] Abre uma modal que exibe suas caracteristicas.
- [ ] As caracteristicas são as mesmas cadastradas anteriormente.

9. Verifique se ao clicar no icone de edicao (lápis) na listagem de equipamentos uma modal para edição é aberta.
- [ ] A modal exibe as informações do mesmo equipamento que foi clicado
- [ ] A modal permite edição dos campos
- [ ] Ao  preencher os campos de maneira errônea, é mostrado um aviso de falha nos campos que devem ser ajustados.
- [ ] Ao clicar em no botão de editar, com todas as informações inceridas corretamente um pop-up é mostrado relatando sucesso.


## Testes finalizados... e agora ?

* Entre nas _issues_ referentes às histórias testadas. Na descrição da US, onde há os **Critérios de Aceitação**, marque todas as caixas de seleção para indicar que os critérios foram atendidos. Ou, caso contrário, faça um comentário para explicar o que está errado ou o que faltou
* Avise também a equipe pelo canal do Discord que esse roteiro foi seguido, executado e finalizado.

## Obrigado!

Qualquer dúvida ou sugestão é só falar conosco pelo Discord.

**Comment by guilhermepupak** [comment]
> # Roteiro para testes do usuário
> 
> História(s) a ser(em) testada(s): **US 01** (#31 ), **US 2**(#36 ), **US 3**(#37 ), **US 4**(#64 ), **US 5**(#50 ), **US 7**(#52 )
> 
> Testadores: Guilherme e Dirlei
> ### Passos para os testes
> 
> Para cada passo executado abaixo, **marque a caixa de seleção** correspondente para indicar a correta execução do que foi pedido.
> 
> **Obs.:** Caso seja necessário indicar mudanças ou não conformidade aos critérios de aceitação da(s) respectiva(s) história(s), responda ao presente roteiro com um comentário, marcando o "@" dos _assignees_ (MDS) e pelo menos um "@" dos EPS.
> 
>     1. Acesse a aplicação em: https://alectrion-2023-1.herokuapp.com/
> 
> 
>     * [ok]  ok
> 
> 
> ### Controle de equipamentos
> 
>     2. Na tela de controle, clique no botão "Cadastrar Equipamento"
> 
> 
>     * [ok]  ok
> 
> 
>     3. Ao cadastrar o equipamento, verifique que, para os equipamentos como "CPU; MONITOR; ESTABILIZADOR e NOBREAK", as seguintes informações adicionais aparecem (cada qual pertinente ao equipamento em questão):
> 
> 
>     * [ok ]  Memória RAM (referente a CPU)
> 
>     * [ok ]  Armazenamento (referente a CPU)
> 
>     * [ok]  Tipo de armazenamento (referente a CPU)
> 
>     * [ok ]  Processador (referente a CPU)
> 
>     * [ok ]  Tipo do monitor (referente a monitor)
> 
>     * ok[ ]  Tamanho do monitor (referente a monitor)
> 
>     * [ok ]  Potência (referente a NoBreak)
> 
> 
>     4. Verifique se apos o correto preenchimento dos campos, ao clicar no botão de "confirmar":
> 
> 
>     * [ok ]  Um pop-up aparece confirmando o sucesso.
**Porém, não consegui cadastar um SCANNER:**
![image](https://github.com/fga-eps-mds/2023-1-Alectrion-DOC/assets/109108065/13812169-8c2d-44b9-a727-b828441c95aa)

> 
> 
>     5. Verifique se apos o preenchimento errado dos campos, ao clicar no botão de "confirmar":
> 
> 
>     * [ ! ]  Um pop-up aparece relatando erro. 
5. **não aparece pop-up. A informação sobre o erro aparece na cor vermelha abaixo do campo específico, que já serve!:**
Gostaria de lembrar que NÚMERO DE SÉRIE deve CONTER LETRAS E NÚMEROS!
![image](https://github.com/fga-eps-mds/2023-1-Alectrion-DOC/assets/109108065/13b31bd5-9806-4044-bbe3-9a49def0a0a6)

> 
> 
>     6. Verifique se apos o sucesso de um cadastro de equipamentos o mesmo aparece na listagem na pagina de controle de equipamentos.
> 
> 
>     * [ok ]  ok
> 
> 
>     7. Verifique se ao clicar no equipamento cadastrado na listagem o mesmo:
> 
> 
>     * [ok ]  Abre uma modal que exibe suas caracteristicas.
> 
>     * [ok ]  As caracteristicas são as mesmas cadastradas anteriormente.
> 
> 
>     8. Verifique se ao clicar no icone de edicao (lápis) na listagem de equipamentos uma modal para edição é aberta.
> 
> 
>     * [ok ]  A modal exibe as informações do mesmo equipamento que foi clicado
> 
>     * [ok ]  A modal permite edição dos campos
> 
>     * [ok ]  Ao  preencher os campos de maneira errônea, é mostrado um aviso de falha nos campos que devem ser ajustados.
> 
>     * [ok ]  Ao clicar em no botão de editar, com todas as informações inceridas corretamente um pop-up é mostrado relatando sucesso.
> 
> 
>     9. Clique em algum equipamento na listagem da página de controle de equipamentos e verifique:
> 
> 
>     * [ok ]  Verifique a presença do botão excluir
> 
>     * [ok ]  Ao clicar no botão de excluir é exibido um pop up para confirmar a ação
> 
>     * [ ! ]  Um pop up de confirmação deve aparecer para confirmar a exclusão
Apareceu o POP-UP, mas o pop-up ficou em vermelho, sem nenhuma informação.
> 
>     * [ ! ]  Verifique se o equipamento foi removido da listagem
A tela travou, tive que atualizar, para então o equipamento sumir da tela de controle de equipamentos.
> 
> 
>     10. Verifique se ao clicar em próximo a tabela é atualizada (se houver equipamentos suficientes cadastrados)
> 
> 
>     * [ ? ]  Ok
Não encontrei o botão **PRÓXIMO**???
> 
> 
>     11. Verifique o funcionamento dos filtros:
> 
> 
>     * [OK ]  Tipo
> 
>     * [OK ]  Última modificação
> 
>     * [ ! ]  Localização
> 
>     * [ ! ]  Situação
> 
>     * [ OK ]  Pesquisa (número de tombamento)
DEVE EXISTIR UM BOTÃO PARA **LIMPAR OS FILTROS**!!!
> 
> 
> ### Movimentação
> 
>     12. Navegue para o movimentação na barra de navegação lateral.
> 
> 
>     * [OK ]  ok
> 
> 
>     13. Na tela de movimentações, clique no botão "Cadastrar Movimentação"
> 
> 
>     * [OK ]  ok
> 
> 
>     14. Verifique se apos o correto preenchimento dos campos, ao clicar no botão de "Gerar Movimentação":
> 
> 
>     * [ ]  Um pop-up aparece confirmando o sucesso.
> 
> 
>     15. Verifique se apos o preenchimento errado dos campos, ao clicar no botão de "Gerar Movimentação":
> 
> 
>     * [ ]  Um pop-up aparece relatando erro.
> 
> 
>     16. Verifique se após o sucesso de um cadastro de movimentação o mesmo aparece na listagem na pagina de Movimentações.
> 
> 
>     * [ ]  ok
> 
> 
>     17. Verifique se ao clicar na movimentação cadastrada na listagem o mesmo:
> 
> 
>     * [ ]  Abre uma modal que exibe suas caracteristicas.
> 
>     * [ ]  As caracteristicas são as mesmas cadastradas anteriormente.
> 
> 
>     18. Verifique se ao clicar em próximo a tabela é atualizada (se houver equipamentos suficientes cadastrados)
> 
> 
>     * [ ]  Ok
> 
> 
>     19. Verifique o funcionamento dos filtros:
> 
> 
>     * [ ]  Tipo
> 
>     * [ ]  Última modificação
> 
>     * [ ]  Localização
> 
>     * [ ]  Situação
> 
>     * [ ]  Pesquisa (número de tombamento)
> 
> 
> ## Testes finalizados... e agora ?
> 
>     * Entre nas _issues_ referentes às histórias testadas. Na descrição da US, onde há os **Critérios de Aceitação**, marque todas as caixas de seleção para indicar que os critérios foram atendidos. Ou, caso contrário, faça um comentário para explicar o que está errado ou o que faltou
> 
>     * Avise também a equipe pelo canal do Discord que esse roteiro foi seguido, executado e finalizado.
> 
> 
> ## Obrigado!
> 
> Qualquer dúvida ou sugestão é só falar conosco pelo Discord.
